name: Build AviSynth+

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {name: "Windows Latest x64", os: windows-latest, cmake-parameters: "-A x64"}
        - {name: "Windows Latest x86", os: windows-latest, cmake-parameters: "-A Win32"}
        - {name: "Ubuntu 22.04 x64", os: ubuntu-22.04}
        - {name: "Ubuntu 24.04 x64", os: ubuntu-24.04}
        - {name: "macOS Latest x64", os: macos-latest}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: ${{ matrix.config.checkout-submodules }}
        fetch-depth: 0

    - name: configure
      run: |
        cmake -S . -B avisynth-build ${{ matrix.config.cmake-parameters }}

    - name: build
      run: |
        cmake --build avisynth-build --config Release -j 2
